# Generated by Django 4.2.6 on 2023-11-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='autor',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='cuerpo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
