# Generated by Django 4.2.6 on 2023-11-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_entrada_autor_alter_entrada_cuerpo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
    ]
