# Generated by Django 4.2.6 on 2023-11-18 13:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_entrada_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
